server:
  port: 8085

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: crud
    password: crud
    auth:
      exchange: auth.exchange
      routingkey:
        main: auth.key
        delete: auth.key.delete
        update: auth.key.update

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  jmx:
    enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/crud?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: sa
    password: 9202157

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    org:
      springframework:
        security: DEBUG