server:
  port: 8085

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: TVhuUhi2Kkoe
    auth:
      exchange: auth.exchange
      routingkey: auth.key
      queue: auth.queue

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  jmx:
    enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/crud?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: sa
    password: 9202157

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
  instance:
    hostname: localhost

logging:
  level:
    org:
      springframework:
        security: DEBUG