server:
  port: 8085

spring:
  application:
    name: email service

  rabbitmq:
    host: 15.228.251.248
    port: 5672
    username: user
    password: TVhuUhi2Kkoe
    auth:
      exchange: auth.exchange
      routingkey: auth.key
      queue: auth.queue

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  jmx:
    enabled: false

  datasource:
    url: jdbc:mysql://devfortechschool.mysql.database.azure.com:3306/crud?useSSL=true&serverTimezone=UTC
    username: devfortech
    password: 34434092jJ.#


eureka:
  client:
    service-url:
      defaultZone: https://devfortech-discovery-discovery.azuremicroservices.io/eureka
    fetch-registry: true
  instance:
    hostname: devfortech-school-crud.azuremicroservices.io
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:8761