server:
  port: 8081
  servlet:
    context-path: /auth

spring:
  rabbitmq:
    host: 15.228.251.248
    port: 5672
    username: user
    password: TVhuUhi2Kkoe
    email:
      exchange: email.exchange
      routingkey: email.send.key
      queue: email.send.queue
    auth:
      exchange: auth.exchange
      routingkey: auth.key
      queue: auth.queue

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://devfortechschool.mysql.database.azure.com:3306/auth?useSSL=true&serverTimezone=UTC
    username: devfortech
    password: 34434092jJ.#

eureka:
  client:
    service-url:
      defaultZone: https://devfortech-school-discovery.azuremicroservices.io/eureka
    fetch-registry: true
  instance:
    hostname: devfortech-school-authorization-service.azuremicroservices.io
    prefer-ip-address: true
