spring:
  application:
    name: gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
  instance:
    hostname: localhost

logging:
  level:
    org:
      springframework:
        security: DEBUG

app:
  authorization:
    url: http://localhost:8081
  crud:
    url: http://localhost:8085