server:
  port: 8761

spring:
  application:
    name: discovery

management:
  server:
    port: ${server.port}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: https://devfortech-school-discovery.azuremicroservices.io/eureka
  instance:
    hostname: devfortech-school-discovery.azuremicroservices.io
    instance-id: ${eureka.instance.hostname}:${spring.application.name}
  environment: prod