server:
  port: 8761

spring:
  application:
    name: discovery

management:
  server:
    port: ${server.port}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: https://devfortech-discovery-discovery.azuremicroservices.io/eureka
  instance:
    prefer-ip-address: true
  environment: prod