spring:
  application:
    name: gateway


eureka:
  client:
    service-url:
      defaultZone: https://devfortech-school-discovery.azuremicroservices.io/eureka
    fetch-registry: true
  instance:
    prefer-ip-address: true

app:
  authorization:
    url: https://devfortech-school-authorization-service.azuremicroservices.io
  crud:
    url: https://devfortech-school-crud.azuremicroservices.io