server:
  port: 8081
  servlet:
    context-path: /auth

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  main:
    allow-circular-references: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true

  jmx:
    enabled: false
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
  instance:
    hostname: localhost
