server:
  port: 8081
  servlet:
    context-path: /auth

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: crud
    password: crud
    email:
      exchange: email.exchange
      routingkey: email.send.key
      queue: email.send.queue
    auth:
      exchange: auth.exchange
      routingkey: auth.key
      queue: auth.queue
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  jmx:
    enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/auth?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: sa
    password: 9202157

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
  instance:
    prefer-ip-address: true


logging:
  level:
    org:
      springframework:
        security: DEBUG
