server:
  port: 8081
  servlet:
    context-path: /auth

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://devfortechschool.mysql.database.azure.com:3306/auth?useSSL=true&serverTimezone=UTC
    username: devfortech
    password: 34434092jJ.#

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
  instance:
    hostname: localhost


logging:
  level:
    org:
      springframework:
        security: DEBUG
