server:
  port: 8100

spring:
  application:
    name: email service

  rabbitmq:
    host: 15.228.251.248
    port: 5672
    username: user
    password: TVhuUhi2Kkoe

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  jmx:
    enabled: false

  datasource:
    url: jdbc:mysql://devfortechschool.mysql.database.azure.com:3306/email-service?useSSL=true&serverTimezone=UTC
    username: devfortech
    password: 34434092jJ.#

  mail:
    host: smtp-relay.sendinblue.com
    port: 587
    username: devfortechschool@gmail.com
    password: dMUE296stOwVBxKn
    protocol: smtp


eureka:
  client:
    service-url:
      defaultZone: https://devfortech-school-discovery.azuremicroservices.io/eureka
    fetch-registry: true
  instance:
    hostname: devfortech-school-authorization-service.azuremicroservices.io
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:8761

email:
  rabbitmq:
    exchange: email.exchange
    queue: email.send.queue