server:
  port: 8100

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  jmx:
    enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/email-service?useSSL=true&serverTimezone=UTC
    username: sa
    password: 9202157

  mail:
    host: smtp-relay.sendinblue.com
    port: 587
    username: devfortechschool@gmail.com
    password: dMUE296stOwVBxKn
    protocol: smtp

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
  instance:
    hostname: localhost

logging:
  level:
    org:
      springframework:
        security: DEBUG

email:
  rabbitmq:
    exchange: email.exchange
    queue: email.send.queue