server:
  port: 8100

spring:
  rabbitmq:
    host: 15.228.251.248
    port: 5672
    username: user
    password: TVhuUhi2Kkoe
    email:
      exchange: email.exchange
      routingkey: email.send.key
      queue: email.send.queue
    auth:
      exchange: auth.exchange
      routingkey: auth.key
      queue: auth.queue

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  jmx:
    enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/email-service?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: sa
    password: 9202157

  mail:
    host: smtp-relay.sendinblue.com
    port: 587
    username: jeferson.black.santos@gmail.com
    password: bpGrW2O3d7cQXS90
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
  instance:
    hostname: localhost

logging:
  level:
    org:
      springframework:
        security: DEBUG

email:
  rabbitmq:
    exchange: email.exchange
    queue: email.send.queue